use_frameworks!

target 'AKFRatingView_Example' do
  pod 'AKFRatingView', :path => '../'

  target 'AKFRatingView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
